# Generated by Django 6.0 on 2025-12-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=254)),
                ('website', models.CharField(max_length=254)),
                ('category', models.CharField(choices=[('Email', 'Email'), ('Work', 'Work'), ('Jobs', 'Jobs'), ('Coding', 'Coding'), ('Health', 'Health'), ('Finance', 'Finance'), ('Bills', 'Bills'), ('Education', 'Education'), ('Travel', 'Travel'), ('Social Media', 'Social Media'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Gaming', 'Gaming'), ('Other', 'Other')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
